### ISSUE TITLE
Could not compile `phf_shared`

### ISSUE THREAD

**Issue by benoittgt** [jiri/rust-emojicons#1]
Update to last rust ?

As mention [here](https://github.com/sfackler/rust-phf/issues/73#issue-124651197) I get some issue when building it. Probably too old. :(

**Comment by jiri** [comment]
Hello! Thanks for the info :smile: I'll see what I can do.

**Comment by jiri** [comment]
I went over the code and did some minor fixes, but I didn't find anything build-breaking.

Please note that rust-emojicons currently only works with _nightly Rust_ versions, because it uses compiler plugins to generate compile-time lookup table for the emoji. Compiler extensions are not as of yet included in the stable and beta Rust versions, which is probably the what's causing your issue in the first place :)

I'm open to any and all pull requests that solve this issue :package:

**Comment by benoittgt** [comment]
Thanks a lot @sindriava for your fast answer. Sadly I'm beginning with rust. It seems quite overskill to try to do a PR for this "issue".

**Comment by jiri** [comment]
@benoittgt Hey! I've got around to rewriting the library from the ground up and it now works on the stable channel :smile: Hope this solves any future issues!

**Comment by benoittgt** [comment]
Thanks a lot @jiri !
